# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class D4s < Formula
  desc "Master Docker like a pro, right from your terminal"
  homepage "https://d4scli.io"
  version "0.42.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jr-k/d4s/releases/download/v0.42.9/d4s_0.42.9_darwin_amd64.tar.gz"
      sha256 "dc4178522a147af6066d0e6385386d46dbec5268ea2a805df0a31d678328cbaf"

      def install
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jr-k/d4s/releases/download/v0.42.9/d4s_0.42.9_darwin_arm64.tar.gz"
      sha256 "55d7770931e6c5d92581275bb215c9a2fd681c2589b52cc2f058dd3575861da2"

      def install
        bin.install "d4s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.42.9/d4s_0.42.9_linux_amd64.tar.gz"
      sha256 "90405fc1f9d1b407d2d34a5b07f25be773caa4eb18b113da03941ca4f7eeb519"
      def install
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.42.9/d4s_0.42.9_linux_arm64.tar.gz"
      sha256 "8df171de36c121495ea2e9b8838c8121e71646c2a017332abc371486a57f5889"
      def install
        bin.install "d4s"
      end
    end
  end
end
