# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class D4s < Formula
  desc "Master Docker like a pro, right from your terminal"
  homepage "https://d4scli.io"
  version "0.49.105"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.105/d4s_0.49.105_darwin_amd64.tar.gz"
      sha256 "a7669dfe5534550e2e3e801125f3a81a18db6d8295cb3fa392cdf4269ddcbf4f"

      define_method(:install) do
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.105/d4s_0.49.105_darwin_arm64.tar.gz"
      sha256 "19051c54323e00d43b0a3199bd84a1789db315f90d6a14ab099b9e12764f7dbc"

      define_method(:install) do
        bin.install "d4s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.105/d4s_0.49.105_linux_amd64.tar.gz"
      sha256 "106a9ba61f94b509b2086ce4c13f8e1c3ae0af521fa265c228c28c22c0c759ef"
      define_method(:install) do
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.105/d4s_0.49.105_linux_armv6.tar.gz"
      sha256 "d27b8ceb95a0210873fdd1774624f4028bc390213c6ade9d27741f2fce26f6dc"
      define_method(:install) do
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.105/d4s_0.49.105_linux_arm64.tar.gz"
      sha256 "842ecb24d9449eefb95c0f089173b78a71bf4b90837b29145983bc2e970efc4b"
      define_method(:install) do
        bin.install "d4s"
      end
    end
  end
end
