# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class D4s < Formula
  desc "Master Docker like a pro, right from your terminal"
  homepage "https://d4scli.io"
  version "0.49.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.21/d4s_0.49.21_darwin_amd64.tar.gz"
      sha256 "69c272d440875b2f3623822c6c358aa37b013fa653fb5e94dedea5d3f71a07ae"

      def install
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.21/d4s_0.49.21_darwin_arm64.tar.gz"
      sha256 "ea33817e7e6251cbd28a8afa7c348b6e5ad1970544c94d0fddd95aba500b0403"

      def install
        bin.install "d4s"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.21/d4s_0.49.21_linux_amd64.tar.gz"
      sha256 "c36ef77a7cc29e2cb0453f8afee86c630cb6268d6eb14032493641918d9e2ee1"
      def install
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.21/d4s_0.49.21_linux_armv6.tar.gz"
      sha256 "27bde22a2193afdd12f1ea1ccd65c391f43d26082746a664b7181df2a9de0024"
      def install
        bin.install "d4s"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jr-k/d4s/releases/download/v0.49.21/d4s_0.49.21_linux_arm64.tar.gz"
      sha256 "2bd3c74c5babb578dfc17302f11766a002b1de9b3b39845d532838153dabdc81"
      def install
        bin.install "d4s"
      end
    end
  end
end
